spring:
  application:
    name: "school_equipment"

# H2 Setting info
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:school
    username: sa
    password: