spring:
  application:
    name: "school_equipment"

# H2 Setting info
  h2:
    console:
      enabled: true
      path: /h2-console


  jpa:
#    defer-datasource-initialization: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate: # query log
#          show_sql: true
#          format_sql: true
#          use_sql_comments: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:school
#    url: jdbc:h2:tcp://localhost/~/school;MODE=MYSQL
    username: sa
    password:

  sql:
    init:
      mode: always # 스키마, 값 Sql 생성

#logging:
#  level:
#    org.hibernate.bind: trace
#    org.hibernate.sql: trace
#    org.hibernate.type.descriptor.sql: trace

