spring:
  application:
    name: "school_equipment"

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration


  datasource: #mysql 설정
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dima?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
#  mvc:
#    static-path-pattern: /static/**
server:
  error:
    whitelabel:
      enabled: false
