create table equipment
(
    equipment_id bigint generated by default as identity ,
    name         varchar not null unique,
    count        integer not null,

    primary key (equipment_id)
);

create table class_time_list
(
    classtimetable_id bigint generated by default as identity ,
    class_name        varchar not null,
    day_of_week       varchar not null,
    one_time          boolean default false,
    two_time          boolean default false,
    three_time        boolean default false,
    four_time         boolean default false,
    five_time         boolean default false,
    six_time          boolean default false,
    seven_time        boolean default false,
    eight_time        boolean default false,
    nine_time         boolean default false,
    ten_time          boolean default false,

    primary key (classtimetable_id)
);


create table rental
(
    rental_id  bigint generated by default as identity ,
    classtimetable_id bigint not null,
    equipment_id bigint not null,
    rental_chk boolean default true,

    foreign key (classtimetable_id) references classTimeList(classtimetable_id),
    foreign key (equipment_id) references equipment(equipment_id),
    primary key (rental_id)
);
