services:
  db:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dima

volumes:
  mysql-data: